source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Switchary_Example', :exclusive => true do
  pod "Switchary", :path => "../"
end

target 'Switchary_Tests', :exclusive => true do
  pod "Switchary", :path => "../"

end
